version: '2.1'
services:
  kafka-connect:
    image: confluentinc/cp-kafka-connect:5.5.1
    hostname: kafka-connect
    networks:
      - internal
    ports:
      - "8083:8083"
      - "7072:7072"
    env_file:
      - connect.env

  kafka-connect-ui:
    image: landoop/kafka-connect-ui:0.9.7
    hostname: kafka-connect-ui
    networks:
      - internal
    ports:
      - "8003:8000"
    environment:
      CONNECT_URL: "http://kafka-connect:8083/"
      PROXY: "true"
    depends_on:
      - kafka-connect

  schema-registry:
    image: confluentinc/cp-schema-registry:5.5.1
    hostname: schema-registry
    container_name: schema-registry
    ports:
      - "8081:8081"
    env_file:
      - registry.env

networks:
  internal:
    driver: bridge